version: '3.3'
services:

  db:
    image: postgres:11.2
    ports:
      - 5432:5432
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=go-money-api
    networks:
      - development-network

  db-ui:
    image: dpage/pgadmin4
    links:
      - db:db
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "boladissimo.dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    depends_on:
      - db
    networks:
      - development-network
      
  redis:
    image: 'bitnami/redis:6.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 6379:6379

networks:
  development-network:
    driver: bridge