version: '3.3'
services:

  db:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: money
      MYSQL_USER: money
      MYSQL_PASSWORD: pass123
    networks:
      - development-network

  db-ui:
    image: adminer:4.8.0
    restart: always
    links:
      - db:db
    ports:
      - 81:8080
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - development-network
      
  redis:
    image: 'bitnami/redis:6.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 6379:6379

networks:
  development-network:
    driver: bridge